name: chattingapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter_dotenv : ^6.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/.env
